version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: music_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 432980146416
      MYSQL_DATABASE: musicstream
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./demo
    container_name: music_backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/musicstream?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 432980146416
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    depends_on:
      - mysql
    volumes:
      - ./demo/songs:/app/songs

  frontend:
    build: ./frontend
    container_name: music_frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  mysql_data:
